### ISSUE TITLE
Can't serialise date object with json.dump

### ISSUE THREAD

**Issue by everald** [PostHog/posthog-migration-tools#2]
**Expected behaviour:**

Finish the migration with an output of last cursor and total events

**Current behaviour:**

Throws an error cause `json.dump` can't serialise the date object within the `last_cursor` object.

**Affected line of code:**

https://github.com/PostHog/posthog-migration-tools/blob/a237e533be41cc1345e2f7dee5b8d5ae0e5d17f1/migrate.py#L330

**Comment by hazzadous** [comment]
Yeah I was doing something silly here, I believe this should be working as expected now.

**Comment by hazzadous** [comment]
This is fixed now 🙏
